version: '3.9'
services:
  mongodb:
    image: zcube/bitnami-compat-mongodb:latest
    env_file:
      - .env.docker
    ports:
      - ${DATABASE_PORT}:${DATABASE_PORT}
    volumes:
      - 'mongodb_data:/bitnami/mongodb'
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - DATABASE_USER
      - DATABASE_PASSWORD
      - DATABASE_NAME
    networks:
      - backend
  backend:
    env_file:
      - .env.docker
    build:
      context: ./
      target: dev
    volumes:
      - .:/src
      - node_modules:/src/node_modules
    command: >
      sh -c "pwd && npm install && /wait && npm run start:debug"
    ports:
      - "${APP_PORT}:${APP_PORT}"
      - "${DEBUG_PORT}:${DEBUG_PORT}"
    depends_on:
      - mongodb
    environment:
      NODE_ENV: development
      DEBUG: backend:*
      WAIT_HOSTS: mongodb:27017
      WAIT_HOSTS_TIMEOUT: 300
      WAIT_SLEEP_INTERVAL: 3
      WAIT_HOST_CONNECT_TIMEOUT: 5
    networks:
      - backend
networks:
  backend:
    driver: bridge
volumes:
  mongodb_data:
    driver: local
  node_modules:
