const DATA_SOURCE = 'DATA_SOURCE';
const REPOSITORY = 'REPOSITORY';

const USER_REPOSITORY = 'USER_REPOSITORY';
const USER_FACTORY = 'USER_FACTORY';

export { DATA_SOURCE, REPOSITORY, USER_REPOSITORY, USER_FACTORY };
